import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Layout from '@/components/Layout'
import profile from '../../public/images/profile/developer-pic-1.png'
import AnimatedText from '@/components/AnimatedText'
import Link from 'next/link'
import { LinkArrow } from '@/components/icons'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main  className='flex items-center text-dark w-full p-12'>

      <Layout>
        <div className='flex flex-row md:flex-col lg:flex-col  items-center justify-between w-full  '>
          <div >
            <Image 
            src={profile} 
            alt="profile" 
            className='w-full h-auto'
            priority
            // sizes="(max-width: 768px) 200vw, (max-width: 1200px) 200vw, 100vw"

            />
          </div>
          <div className=" xl:w-full md:w-full w-1/2 flex items-center flex-col self-center p-6 ">
            <AnimatedText 
            text="Turning Vision Into Reality With Code And Design. "
            className='text-6xl 
            text-left mb-3 sm:w-[100%] lg:text-xl sm:text-sm xs:text-xs  2xl:w-[100%] '/>
           <p className='text-base  xs:text-sm md:text-lg lg:text-xl xl:text-2xl  font-medium my-4'>

              As a skilled full-stack developer, I am dedicated to turning ideas into innovative web applications. 
Explore my latest projects and articles, showcasing my expertise in React.js and web development.</p>
<div className='flex items-center self-start mt-2'>
            <Link
            className='flex items-center bg-dark text-light rounded-lg font-semibold hover:bg-light
             hover:text-dark border-2 border-solid border-transparent p-3  mr-3  px-6 '
             download={true}
             href="/" target={"_blank"}>Resume
             <LinkArrow className="w-6 ml-3"/>
             </Link>
            <Link href="/" 
            className='font-medium text-lg underline'
            target={"_blank"}>Contact</Link>
          </div>
          </div>
          

        </div>
        </Layout>
        
        
      </main>
    </>
  )
}
